/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const APP_START_OK_EVENT: typeof import('./src/stores/app').APP_START_OK_EVENT
  const CHANNEL_INSTANCE_GROUP_CREATE_EVENT: typeof import('./src/stores/channelInstances').CHANNEL_INSTANCE_GROUP_CREATE_EVENT
  const CHANNEL_INSTANCE_MOVE_TO_WINDOW_EVENT: typeof import('./src/stores/channelInstances').CHANNEL_INSTANCE_MOVE_TO_WINDOW_EVENT
  const CONCURRENCY_MAX: typeof import('./src/stores/downloadStore').CONCURRENCY_MAX
  const CONCURRENCY_MIN: typeof import('./src/stores/downloadStore').CONCURRENCY_MIN
  const ChannelInstanceProvideKey: typeof import('./src/utils/constant').ChannelInstanceProvideKey
  const CustomMenusEventKey: typeof import('./src/utils/constant').CustomMenusEventKey
  const DEFAULT_FONT_FAMILY: typeof import('./src/utils/constant').DEFAULT_FONT_FAMILY
  const DEFAULT_UI_FONT_SIZE: typeof import('./src/utils/fontSize').DEFAULT_UI_FONT_SIZE
  const EDIT_SERVER_SAVED_EVENT: typeof import('./src/utils/window').EDIT_SERVER_SAVED_EVENT
  const EffectScope: typeof import('vue').EffectScope
  const MONACO_EDITOR_ADD_ITEM: typeof import('./src/utils/window').MONACO_EDITOR_ADD_ITEM
  const MONACO_EDITOR_SAVED_EVENT: typeof import('./src/utils/window').MONACO_EDITOR_SAVED_EVENT
  const Monaco: typeof import("./src/utils/constant").Monaco
  const PRIORITY_HIGH: typeof import('./src/stores/keyEvent').PRIORITY_HIGH
  const PRIORITY_HIGHEST: typeof import('./src/stores/keyEvent').PRIORITY_HIGHEST
  const PRIORITY_LOW: typeof import('./src/stores/keyEvent').PRIORITY_LOW
  const PRIORITY_LOWEST: typeof import('./src/stores/keyEvent').PRIORITY_LOWEST
  const PRIORITY_MEDIUM: typeof import('./src/stores/keyEvent').PRIORITY_MEDIUM
  const RECENTLY_SERVER_DATA_CACHE_KEY: typeof import('./src/stores/serverData').RECENTLY_SERVER_DATA_CACHE_KEY
  const RUNTIME_CACHE_FILE: typeof import('./src/stores/localstore').RUNTIME_CACHE_FILE
  const SERVER_CHANGED_EVENT: typeof import('./src/stores/serverData').SERVER_CHANGED_EVENT
  const SERVER_TREE_CLICK_SERVER_EVENT: typeof import('./src/stores/channelInstances').SERVER_TREE_CLICK_SERVER_EVENT
  const SETTINGS_WEBVIEW_LABEL: typeof import("./src/utils/window").SETTINGS_WEBVIEW_LABEL
  const SftpActiveItemKey: typeof import('./src/utils/constant').SftpActiveItemKey
  const UPLOAD_CONFLICT_DATA_EVENT: typeof import('./src/utils/window').UPLOAD_CONFLICT_DATA_EVENT
  const UPLOAD_CONFLICT_RESOLVED_EVENT: typeof import('./src/utils/window').UPLOAD_CONFLICT_RESOLVED_EVENT
  const UiPreferencesSavedEventKey: typeof import('./src/utils/constant').UiPreferencesSavedEventKey
  const WEBVIEW_INIT_DATA_EVENT: typeof import('./src/utils/window').WEBVIEW_INIT_DATA_EVENT
  const applyUiFontSize: typeof import('./src/utils/fontSize').applyUiFontSize
  const awaiting: typeof import('./src/utils/index').awaiting
  const base64ToUtf8: typeof import('./src/utils/project').base64ToUtf8
  const baseName: typeof import('./src/utils/fsUtil').baseName
  const buildDeleteConfirmMessage: typeof import('./src/utils/confirmMessage').buildDeleteConfirmMessage
  const buildDownloadFileRemoteCmd: typeof import("./src/utils/fsUtil").buildDownloadFileRemoteCmd
  const buildListDirRemoteCmd: typeof import("./src/utils/fsUtil").buildListDirRemoteCmd
  const buildListSubDirsRemoteCmd: typeof import("./src/utils/fsUtil").buildListSubDirsRemoteCmd
  const buildMoveConfirmMessage: typeof import('./src/utils/confirmMessage').buildMoveConfirmMessage
  const buildResolveHomeRemoteCmd: typeof import("./src/utils/fsUtil").buildResolveHomeRemoteCmd
  const buildUploadFileRemoteCmd: typeof import("./src/utils/fsUtil").buildUploadFileRemoteCmd
  const calculateSpeedBps: typeof import('./src/utils/index').calculateSpeedBps
  const checkLinuxFileName: typeof import('./src/utils/fsUtil').checkLinuxFileName
  const computed: typeof import('vue').computed
  const copy: typeof import("./src/utils/project").copy
  const copyText: typeof import('./src/utils/project').copyText
  const countdownText: typeof import('./src/utils/index').countdownText
  const countdownTextDay: typeof import("./src/utils/index").countdownTextDay
  const createApp: typeof import('vue').createApp
  const createDefaultServerOverview: typeof import('./src/utils/serverOverviewPolling').createDefaultServerOverview
  const createNewWindow: typeof import("./src/utils/window").createNewWindow
  const createOverview: typeof import('./src/utils/serverOverviewPolling').createOverview
  const customRef: typeof import('vue').customRef
  const decodePathCmd: typeof import("./src/utils/fsUtil").decodePathCmd
  const deepClone: typeof import('./src/utils/index').deepClone
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const downloadRemoteFileBase64: typeof import("./src/utils/fsUtil").downloadRemoteFileBase64
  const dragListener: typeof import('./src/utils/project').dragListener
  const effectScope: typeof import('vue').effectScope
  const eventHave: typeof import('./src/utils/project').eventHave
  const execRemote: typeof import('./src/utils/project').execRemote
  const extractCdTargets: typeof import("./src/utils/termCwd").extractCdTargets
  const formatAdaptiveBytes: typeof import('./src/utils/project').formatAdaptiveBytes
  const formatSpeedBps: typeof import('./src/utils/project').formatSpeedBps
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getCurrentWindowScaleFactor: typeof import('./src/utils/project').getCurrentWindowScaleFactor
  const getFileDirPath: typeof import('./src/utils/localFsUtils').getFileDirPath
  const getMainWinLabel: typeof import("./src/utils/window").getMainWinLabel
  const getOverview: typeof import('./src/utils/serverOverviewPolling').getOverview
  const getUiFontSizeCss: typeof import('./src/utils/fontSize').getUiFontSizeCss
  const h: typeof import('vue').h
  const ingestRemoteOverviewCore: typeof import('./src/utils/serverOverviewPolling').ingestRemoteOverviewCore
  const ingestRemoteOverviewDisks: typeof import('./src/utils/serverOverviewPolling').ingestRemoteOverviewDisks
  const ingestRemoteOverviewNet: typeof import('./src/utils/serverOverviewPolling').ingestRemoteOverviewNet
  const ingestRemoteOverviewProcesses: typeof import('./src/utils/serverOverviewPolling').ingestRemoteOverviewProcesses
  const initialState: typeof import('./src/stores/config').initialState
  const inject: typeof import('vue').inject
  const invoke: typeof import('./src/utils/project').invoke
  const isChannelInstance: typeof import('./src/stores/channelInstances').isChannelInstance
  const isChannelInstanceGroup: typeof import('./src/stores/channelInstances').isChannelInstanceGroup
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const joinSlash: typeof import("./src/utils/fsUtil").joinSlash
  const linuxPathToLocalPath: typeof import('./src/utils/localFsUtils').linuxPathToLocalPath
  const listRemoteDir: typeof import("./src/utils/fsUtil").listRemoteDir
  const listRemoteSubDirs: typeof import("./src/utils/fsUtil").listRemoteSubDirs
  const listRemoteSubFiles: typeof import('./src/utils/fsUtil').listRemoteSubFiles
  const localFileByteSize: typeof import('./src/utils/localFsUtils').localFileByteSize
  const localPathToLinuxPath: typeof import('./src/utils/localFsUtils').localPathToLinuxPath
  const mainLabels: typeof import('./src/utils/window').mainLabels
  const mainWinLabel: typeof import("./src/utils/window").mainWinLabel
  const mapGet: typeof import('./src/utils/index').mapGet
  const markRaw: typeof import('vue').markRaw
  const moduleBoxInit: typeof import("./src/utils/layout").moduleBoxInit
  const monospace: typeof import("./src/utils/constant").monospace
  const nextTick: typeof import('vue').nextTick
  const normalizePosixPath: typeof import('./src/utils/termCwd').normalizePosixPath
  const normalizeTreePath: typeof import("./src/utils/fsUtil").normalizeTreePath
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const oneFileRemoteItem: typeof import('./src/utils/fsUtil').oneFileRemoteItem
  const openFileWithSystem: typeof import("./src/utils/localFsUtils").openFileWithSystem
  const openOrFocusChildWindow: typeof import('./src/utils/window').openOrFocusChildWindow
  const openOrFocusEditServerWindow: typeof import('./src/utils/window').openOrFocusEditServerWindow
  const openOrFocusMonacoEditorWindow: typeof import('./src/utils/window').openOrFocusMonacoEditorWindow
  const openOrFocusServerTreeWindow: typeof import('./src/utils/window').openOrFocusServerTreeWindow
  const openOrFocusSettingsWindow: typeof import('./src/utils/window').openOrFocusSettingsWindow
  const openUploadConflictWindow: typeof import('./src/utils/window').openUploadConflictWindow
  const padZero: typeof import('./src/utils/index').padZero
  const parentDirSlash: typeof import('./src/utils/fsUtil').parentDirSlash
  const parseCdArg: typeof import("./src/utils/termCwd").parseCdArg
  const parseOsc7Cwd: typeof import('./src/utils/termCwd').parseOsc7Cwd
  const parseRemoteSubFile: typeof import("./src/utils/fsUtil").parseRemoteSubFile
  const pathAllParentPaths: typeof import('./src/utils/fsUtil').pathAllParentPaths
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readClipboardText: typeof import('./src/utils/project').readClipboardText
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const remoteCopy: typeof import('./src/utils/fsUtil').remoteCopy
  const remoteCreateFile: typeof import('./src/utils/fsUtil').remoteCreateFile
  const remoteJoin: typeof import('./src/utils/fsUtil').remoteJoin
  const remoteMkdir: typeof import('./src/utils/fsUtil').remoteMkdir
  const remoteMove: typeof import('./src/utils/fsUtil').remoteMove
  const remoteRemove: typeof import('./src/utils/fsUtil').remoteRemove
  const remoteRename: typeof import('./src/utils/fsUtil').remoteRename
  const removeArrayItem: typeof import('./src/utils/index').removeArrayItem
  const removeLocalIfAny: typeof import('./src/utils/localFsUtils').removeLocalIfAny
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveRemoteCdPath: typeof import("./src/utils/termCwd").resolveRemoteCdPath
  const resolveRemoteHome: typeof import('./src/utils/fsUtil').resolveRemoteHome
  const sans: typeof import("./src/utils/constant").sans
  const scanRemoteTree: typeof import('./src/utils/fsUtil').scanRemoteTree
  const setOverviewError: typeof import('./src/utils/serverOverviewPolling').setOverviewError
  const setOverviewIface: typeof import('./src/utils/serverOverviewPolling').setOverviewIface
  const settingStyle: typeof import('./src/utils/project').settingStyle
  const sftpDownloadFile: typeof import("./src/utils/fsUtil").sftpDownloadFile
  const sftpReadAllBase64: typeof import("./src/utils/fsUtil").sftpReadAllBase64
  const sftpReadChunkBase64: typeof import("./src/utils/fsUtil").sftpReadChunkBase64
  const sftpReadFileStream: typeof import('./src/utils/fsUtil').sftpReadFileStream
  const sftpSha256: typeof import("./src/utils/fsUtil").sftpSha256
  const sftpStat: typeof import("./src/utils/fsUtil").sftpStat
  const sftpTransferCancel: typeof import("./src/utils/fsUtil").sftpTransferCancel
  const sftpTransferPause: typeof import("./src/utils/fsUtil").sftpTransferPause
  const sftpWriteChunkBase64: typeof import("./src/utils/fsUtil").sftpWriteChunkBase64
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shellSingleQuote: typeof import('./src/utils/project').shellSingleQuote
  const showConfirm: typeof import('./src/utils/ui').showConfirm
  const showErrorToast: typeof import("./src/utils/project").showErrorToast
  const showPermissionEditor: typeof import("./src/utils/ui").showPermissionEditor
  const showPrompt: typeof import('./src/utils/ui').showPrompt
  const showToast: typeof import('./src/utils/ui').showToast
  const sleep: typeof import('./src/utils/index').sleep
  const supportsNativeWindowGlass: typeof import('./src/utils/windowGlass').supportsNativeWindowGlass
  const syncWindowGlass: typeof import('./src/utils/windowGlass').syncWindowGlass
  const syncWindowTransparent: typeof import('./src/utils/windowGlass').syncWindowTransparent
  const terminalDataToString: typeof import('./src/utils/termCwd').terminalDataToString
  const toPermBits: typeof import("./src/utils/fsUtil").toPermBits
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const treeForEach: typeof import('./src/utils/index').treeForEach
  const treeForEachAsync: typeof import('./src/utils/index').treeForEachAsync
  const treeForEachDeep: typeof import('./src/utils/index').treeForEachDeep
  const treeForEachDeepAsync: typeof import('./src/utils/index').treeForEachDeepAsync
  const treeForMap: typeof import('./src/utils/index').treeForMap
  const treeList2Tree: typeof import('./src/utils/index').treeList2Tree
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const uploadRemoteFileBase64: typeof import("./src/utils/fsUtil").uploadRemoteFileBase64
  const useAppStore: typeof import('./src/stores/app').useAppStore
  const useAttrs: typeof import('vue').useAttrs
  const useChannelInstancesStore: typeof import('./src/stores/channelInstances').useChannelInstancesStore
  const useConfigStore: typeof import('./src/stores/config').useConfigStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDownloadStore: typeof import('./src/stores/downloadStore').useDownloadStore
  const useId: typeof import('vue').useId
  const useKeyEventStore: typeof import('./src/stores/keyEvent').useKeyEventStore
  const useLink: typeof import('vue-router').useLink
  const useLocalStore: typeof import('./src/stores/localstore').useLocalStore
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useServerDataStore: typeof import('./src/stores/serverData').useServerDataStore
  const useServerOverviewStore: typeof import('./src/stores/serverOverview').useServerOverviewStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const utf8ToBase64: typeof import('./src/utils/project').utf8ToBase64
  const uuid: typeof import('./src/utils/index').uuid
  const viwerBoxSetting: typeof import("./src/utils/layout").viwerBoxSetting
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const writeLocalFileToRemote: typeof import('./src/utils/fsUtil').writeLocalFileToRemote
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { RemoteFileItem } from './src/utils/fsUtil'
  import('./src/utils/fsUtil')
  // @ts-ignore
  export type { Spread, TreeItemBase, TreeListItem, CountdownTextStyle } from './src/utils/index'
  import('./src/utils/index')
  // @ts-ignore
  export type { OverviewProcessSort, ServerOverviewState } from './src/utils/serverOverviewPolling'
  import('./src/utils/serverOverviewPolling')
  // @ts-ignore
  export type { ConfirmMessage } from './src/utils/ui'
  import('./src/utils/ui')
  // @ts-ignore
  export type { AppType, EditServerWindowPayload, EditServerSavedPayload, MonacoEditorWindowPayload, MonacoEditorSavedPayload, UploadConflictAction, UploadConflictWindowPayload, UploadConflictResolvedPayload, ChildWindowPayload } from './src/utils/window'
  import('./src/utils/window')
  // @ts-ignore
  export type { AppStartOkPayload } from './src/stores/app'
  import('./src/stores/app')
  // @ts-ignore
  export type { ServerTreeClickServerPayload, ChannelInstanceGroupType, ChannelInstanceGroupCreatePayload, ChannelInstanceMoveToWindowPayload, ChannelInstance, ChannelInstanceGroup, ChannelData } from './src/stores/channelInstances'
  import('./src/stores/channelInstances')
  // @ts-ignore
  export type { Theme, ThemeMode, ServerSyncType, ServerRemoteData, ConfigModel } from './src/stores/config'
  import('./src/stores/config')
  // @ts-ignore
  export type { TransferStatus, TransferKind, SftpPaneTransferBinding, ByteProgressMeta, LoadingFlag, TransferItem, DownloadStore } from './src/stores/downloadStore'
  import('./src/stores/downloadStore')
  // @ts-ignore
  export type { Priority, KeyEventCallback } from './src/stores/keyEvent'
  import('./src/stores/keyEvent')
  // @ts-ignore
  export type { PrivateKeyModel, ServerGroupModel, ServerDataModel, ServerRustModel, ServerDataExportModel, ServerDataSyncModel, RowData } from './src/stores/serverData'
  import('./src/stores/serverData')
}
