/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Channels: typeof import('./src/components/ssh/Channels.vue')['default']
    ChildWin: typeof import('./src/components/window/ChildWin.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    DefaultLayout: typeof import('./src/layout/DefaultLayout.vue')['default']
    DefaultMenuItems: typeof import('./src/components/DefaultMenuItems.vue')['default']
    DefaultMenus: typeof import('./src/components/DefaultMenus.vue')['default']
    EditServerWin: typeof import('./src/components/window/EditServerWin.vue')['default']
    GlobalButton: typeof import('./src/components/GlobalButton.vue')['default']
    GlobalLoadingText: typeof import('./src/components/GlobalLoadingText.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    LayoutColumnResizer: typeof import('./src/components/layout/LayoutColumnResizer.vue')['default']
    LayoutRowResizer: typeof import('./src/components/layout/LayoutRowResizer.vue')['default']
    MainWin: typeof import('./src/components/window/MainWin.vue')['default']
    MonacoEditor: typeof import('./src/components/monaco/MonacoEditor.vue')['default']
    MonacoEditorTabs: typeof import('./src/components/monaco/MonacoEditorTabs.vue')['default']
    MonacoWin: typeof import('./src/components/window/MonacoWin.vue')['default']
    PermissionEditor: typeof import('./src/components/PermissionEditor.vue')['default']
    Prompt: typeof import('./src/components/Prompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDisk: typeof import('./src/components/ssh/ServerDisk.vue')['default']
    ServerList: typeof import('./src/components/ServerList.vue')['default']
    ServerMessage: typeof import('./src/components/ssh/ServerMessage.vue')['default']
    ServerOverviewPanel: typeof import('./src/components/ssh/ServerOverviewPanel.vue')['default']
    ServerResource: typeof import('./src/components/ssh/ServerResource.vue')['default']
    ServerTree: typeof import('./src/components/ServerTree.vue')['default']
    ServerTreeRow: typeof import('./src/components/ServerTreeRow.vue')['default']
    ServerTreeWin: typeof import('./src/components/window/ServerTreeWin.vue')['default']
    SettingDialog: typeof import('./src/components/SettingDialog.vue')['default']
    SettingWin: typeof import('./src/components/window/SettingWin.vue')['default']
    Sftp: typeof import('./src/components/sftp/Sftp.vue')['default']
    SftpDirTree: typeof import('./src/components/sftp/SftpDirTree.vue')['default']
    SftpDirTreeItem: typeof import('./src/components/sftp/SftpDirTreeItem.vue')['default']
    SftpFileTable: typeof import('./src/components/sftp/SftpFileTable.vue')['default']
    SftpToolbar: typeof import('./src/components/sftp/SftpToolbar.vue')['default']
    SftpTransferItem: typeof import('./src/components/sftp/SftpTransferItem.vue')['default']
    SftpTransfersTab: typeof import('./src/components/sftp/SftpTransfersTab.vue')['default']
    ShellInstance: typeof import('./src/components/ssh/ShellInstance.vue')['default']
    Term: typeof import('./src/components/ssh/term.vue')['default']
    UploadConflictWin: typeof import('./src/components/window/UploadConflictWin.vue')['default']
    WindowTitleBar: typeof import('./src/components/WindowTitleBar.vue')['default']
  }
}

// For TSX support
declare global {
  const Channels: typeof import('./src/components/ssh/Channels.vue')['default']
  const ChildWin: typeof import('./src/components/window/ChildWin.vue')['default']
  const Confirm: typeof import('./src/components/Confirm.vue')['default']
  const DefaultLayout: typeof import('./src/layout/DefaultLayout.vue')['default']
  const DefaultMenuItems: typeof import('./src/components/DefaultMenuItems.vue')['default']
  const DefaultMenus: typeof import('./src/components/DefaultMenus.vue')['default']
  const EditServerWin: typeof import('./src/components/window/EditServerWin.vue')['default']
  const GlobalButton: typeof import('./src/components/GlobalButton.vue')['default']
  const GlobalLoadingText: typeof import('./src/components/GlobalLoadingText.vue')['default']
  const Icon: typeof import('./src/components/Icon.vue')['default']
  const LayoutColumnResizer: typeof import('./src/components/layout/LayoutColumnResizer.vue')['default']
  const LayoutRowResizer: typeof import('./src/components/layout/LayoutRowResizer.vue')['default']
  const MainWin: typeof import('./src/components/window/MainWin.vue')['default']
  const MonacoEditor: typeof import('./src/components/monaco/MonacoEditor.vue')['default']
  const MonacoEditorTabs: typeof import('./src/components/monaco/MonacoEditorTabs.vue')['default']
  const MonacoWin: typeof import('./src/components/window/MonacoWin.vue')['default']
  const PermissionEditor: typeof import('./src/components/PermissionEditor.vue')['default']
  const Prompt: typeof import('./src/components/Prompt.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const ServerDisk: typeof import('./src/components/ssh/ServerDisk.vue')['default']
  const ServerList: typeof import('./src/components/ServerList.vue')['default']
  const ServerMessage: typeof import('./src/components/ssh/ServerMessage.vue')['default']
  const ServerOverviewPanel: typeof import('./src/components/ssh/ServerOverviewPanel.vue')['default']
  const ServerResource: typeof import('./src/components/ssh/ServerResource.vue')['default']
  const ServerTree: typeof import('./src/components/ServerTree.vue')['default']
  const ServerTreeRow: typeof import('./src/components/ServerTreeRow.vue')['default']
  const ServerTreeWin: typeof import('./src/components/window/ServerTreeWin.vue')['default']
  const SettingDialog: typeof import('./src/components/SettingDialog.vue')['default']
  const SettingWin: typeof import('./src/components/window/SettingWin.vue')['default']
  const Sftp: typeof import('./src/components/sftp/Sftp.vue')['default']
  const SftpDirTree: typeof import('./src/components/sftp/SftpDirTree.vue')['default']
  const SftpDirTreeItem: typeof import('./src/components/sftp/SftpDirTreeItem.vue')['default']
  const SftpFileTable: typeof import('./src/components/sftp/SftpFileTable.vue')['default']
  const SftpToolbar: typeof import('./src/components/sftp/SftpToolbar.vue')['default']
  const SftpTransferItem: typeof import('./src/components/sftp/SftpTransferItem.vue')['default']
  const SftpTransfersTab: typeof import('./src/components/sftp/SftpTransfersTab.vue')['default']
  const ShellInstance: typeof import('./src/components/ssh/ShellInstance.vue')['default']
  const Term: typeof import('./src/components/ssh/term.vue')['default']
  const UploadConflictWin: typeof import('./src/components/window/UploadConflictWin.vue')['default']
  const WindowTitleBar: typeof import('./src/components/WindowTitleBar.vue')['default']
}